#!/bin/bash

which curl >/dev/null
if [[ "$?" != "0" ]];then
    echo "curl is not installed. Please install curl before."
    exit
fi

bash <(curl https://github.com/TranslucentFoxHuman/System-Easy-Setup-Script/raw/refs/heads/devel/debian.bash)